name = "gleev-proxy-worker"
type = "javascript"
account_id = ""
route = ""
compatibility_date = "2022-12-19"
workers_dev = true

[vars]
ATLAS_URL = "https://gleev.vercel.app"
META_SERVER_URL = "https://atlas-services.joystream.org/social-previews"

[build]
command = "yarn install --immutable && yarn build"
[build.upload]
format = "service-worker"

[env.production]
zone_id = "2b896d6b020ebdabb8f56a17d864ba18"
routes = ["gleev.xyz/channel/*", "gleev.xyz/video/*", "gleev.xyz/ypp"]

[env.production.vars]
ATLAS_URL = "https://gleev.vercel.app"
META_SERVER_URL = "https://atlas-services.joystream.org/social-previews"
