// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgAppLogoShort = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={104} height={88} viewBox="0 0 104 88" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <g clipPath="url(#clip0_1546_25585)">
      <path
        d="M71 44 37 0h28.108a12 12 0 0 1 9.495 4.663L104 42.706 102.47 44H71Z"
        fill="url(#paint0_linear_1546_25585)"
      />
      <path
        d="M71 44 37 0h28.108a12 12 0 0 1 9.495 4.663L104 42.706 102.47 44H71Z"
        fill="url(#paint1_radial_1546_25585)"
      />
      <path
        d="M71 44H39.53l-.985 2 10.258 13.274a11 11 0 0 1 0 13.452L37 88h28.108a12 12 0 0 0 9.495-4.663l7.255-9.388a13 13 0 0 0 0-15.898L71 44Z"
        fill="url(#paint2_linear_1546_25585)"
      />
      <path
        d="M33.869 0a12 12 0 0 0-9.472 4.633L4.912 29.685a23.316 23.316 0 0 0 0 28.63l19.485 25.052A12 12 0 0 0 33.869 88h31.239c.464 0 .925-.027 1.38-.08a12 12 0 0 1-8.091-4.553L37.122 56.014a19.569 19.569 0 0 1 0-24.028L58.397 4.633A12 12 0 0 1 66.488.08c-.455-.053-.916-.08-1.38-.08H33.868Z"
        fill="url(#paint3_linear_1546_25585)"
      />
      <path
        d="M33.869 0a12 12 0 0 0-9.472 4.633L4.912 29.685a23.316 23.316 0 0 0 0 28.63l19.485 25.052A12 12 0 0 0 33.869 88h31.239c.464 0 .925-.027 1.38-.08a12 12 0 0 1-8.091-4.553L37.122 56.014a19.569 19.569 0 0 1 0-24.028L58.397 4.633A12 12 0 0 1 66.488.08c-.455-.053-.916-.08-1.38-.08H33.868Z"
        fill="url(#paint4_radial_1546_25585)"
        fillOpacity={0.5}
      />
      <path d="M71 44H39.532l-.982 2h31.468L71 44Z" fill="url(#paint5_linear_1546_25585)" />
      <path d="M38.714 45.667h31.468l-.164.333H38.55l.164-.333Z" fill="#2F2BAD" />
      <path
        d="M65.222 0a12 12 0 0 1 9.38 4.663L104 42.706 102.472 44 73.02 5.885a10 10 0 0 0-7.798-3.884 10 10 0 0 0-7.78 3.86L37.12 31.993a19.558 19.558 0 0 0 0 24.014l20.323 26.132a10 10 0 0 0 7.78 3.86 10 10 0 0 0 7.798-3.885l7.255-9.388a11 11 0 0 0 0-13.452L70.018 46 71 44 81.858 58.05a13 13 0 0 1 0 15.898l-7.255 9.388A12 12 0 0 1 65.222 88a12 12 0 0 1-9.359-4.632L35.541 57.234a21.558 21.558 0 0 1 0-26.469L55.862 4.633A12 12 0 0 1 65.222 0Z"
        fill="url(#paint6_linear_1546_25585)"
      />
      <path
        d="M65.388.003A12.005 12.005 0 0 0 65.222 0a12 12 0 0 0-9.359 4.633L35.541 30.765a21.558 21.558 0 0 0 0 26.47l20.322 26.132a12 12 0 0 0 9.359 4.632l.166-.002a12 12 0 0 1-9.191-4.63L35.874 57.234a21.558 21.558 0 0 1 0-26.469L56.197 4.633a12 12 0 0 1 9.191-4.63Z"
        fill="url(#paint7_linear_1546_25585)"
      />
      <path
        d="M102.674 43.83 73.354 5.884a10 10 0 0 0-7.799-3.884l-.167.003a10 10 0 0 1 7.632 3.881L102.472 44l.202-.17Z"
        fill="url(#paint8_linear_1546_25585)"
      />
      <path
        d="m65.388 85.996.167.003a10 10 0 0 0 7.799-3.885l7.255-9.388a11 11 0 0 0 0-13.452L70.35 46l.853-1.736L71 44l-.982 2 10.257 13.274a11 11 0 0 1 0 13.452l-7.255 9.388a10 10 0 0 1-7.632 3.882Z"
        fill="url(#paint9_linear_1546_25585)"
      />
    </g>
    <defs>
      <linearGradient id="paint0_linear_1546_25585" x1={70.5} y1={0} x2={70.5} y2={44} gradientUnits="userSpaceOnUse">
        <stop offset={0.054} stopColor="#181759" />
        <stop offset={0.188} stopColor="#242189" />
        <stop offset={1} stopColor="#201D7F" />
      </linearGradient>
      <linearGradient id="paint2_linear_1546_25585" x1={62.5} y1={88} x2={62.5} y2={44} gradientUnits="userSpaceOnUse">
        <stop stopColor="#3836A6" />
        <stop offset={0.184} stopColor="#242291" />
        <stop offset={0.388} stopColor="#2B29A3" />
        <stop offset={0.478} stopColor="#3330B7" />
        <stop offset={0.599} stopColor="#3330B7" />
        <stop offset={0.73} stopColor="#201E8E" />
      </linearGradient>
      <linearGradient id="paint3_linear_1546_25585" x1={34} y1={0} x2={34} y2={88} gradientUnits="userSpaceOnUse">
        <stop stopColor="#AFADF2" />
        <stop offset={0.066} stopColor="#504DC7" />
        <stop offset={0.293} stopColor="#3834AC" />
        <stop offset={0.384} stopColor="#2F2BAE" />
        <stop offset={0.481} stopColor="#332FB6" />
        <stop offset={0.562} stopColor="#2F2BAF" />
        <stop offset={0.653} stopColor="#1F1C80" />
        <stop offset={0.937} stopColor="#1A1871" />
        <stop offset={1} stopColor="#0D0C31" />
      </linearGradient>
      <linearGradient id="paint5_linear_1546_25585" x1={38.5} y1={45} x2={70.5} y2={45} gradientUnits="userSpaceOnUse">
        <stop stopColor="#fff" />
        <stop offset={0} stopColor="#222085" />
        <stop offset={1} stopColor="#3532A9" />
      </linearGradient>
      <linearGradient id="paint6_linear_1546_25585" x1={31} y1={0} x2={104} y2={88} gradientUnits="userSpaceOnUse">
        <stop stopColor="#6159E4" />
        <stop offset={1} stopColor="#4A43D5" />
      </linearGradient>
      <linearGradient
        id="paint7_linear_1546_25585"
        x1={66.837}
        y1={0}
        x2={66.837}
        y2={87.999}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#958AFF" />
        <stop offset={0.5} stopColor="#958AFF" />
        <stop offset={1} stopColor="#958AFF" />
      </linearGradient>
      <linearGradient
        id="paint8_linear_1546_25585"
        x1={66.837}
        y1={0}
        x2={66.837}
        y2={87.999}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#958AFF" />
        <stop offset={0.5} stopColor="#958AFF" />
        <stop offset={1} stopColor="#958AFF" />
      </linearGradient>
      <linearGradient
        id="paint9_linear_1546_25585"
        x1={66.837}
        y1={0}
        x2={66.837}
        y2={87.999}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#958AFF" />
        <stop offset={0.5} stopColor="#958AFF" />
        <stop offset={1} stopColor="#958AFF" />
      </linearGradient>
      <radialGradient
        id="paint1_radial_1546_25585"
        cx={0}
        cy={0}
        r={1}
        gradientUnits="userSpaceOnUse"
        gradientTransform="matrix(18.49996 44 -39.27551 16.51354 52 0)"
      >
        <stop stopColor="#111048" />
        <stop offset={0.637} stopColor="#111048" stopOpacity={0} />
      </radialGradient>
      <radialGradient
        id="paint4_radial_1546_25585"
        cx={0}
        cy={0}
        r={1}
        gradientUnits="userSpaceOnUse"
        gradientTransform="rotate(147.095 34 10.04) scale(80.9938 62.5861)"
      >
        <stop stopColor="#BDBBEF" />
        <stop offset={0.698} stopColor="#9896DF" stopOpacity={0} />
      </radialGradient>
      <clipPath id="clip0_1546_25585">
        <path fill="#fff" d="M0 0h104v88H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgAppLogoShort.displayName = 'SvgAppLogoShort'
const Memo = memo(SvgAppLogoShort)
export { Memo as SvgAppLogoShort }
